### ISSUE TITLE
Define outputs

### ISSUE THREAD

**Issue by whit537** [sustainers/website#118]
Raised by @jaredhanson underneath #56:

> I would love to attend this event, but unfortunately I am attending another conference (Cloud Identity Summit) on the same date.  Will the sessions be recorded and made available?  Would definitely like to follow the conversation.

@alnermcgunn What sort of outputs should we expect from Aspiration's process?

**Comment by alnermcgunn** [comment]
We can discuss on call today. Our normal model is just session notes and post event synthesis of the same. We don't film sessions because remote user experience is low, and it has chilling effect on sessions. Happy to discuss other outputs, but long story short, remote participation is essentially not a supported feature of our model.

**Comment by whit537** [comment]
Session notes from each session, based on input from participants.

**Comment by whit537** [comment]
Normal pattern is to start with etherpads, and consolidate to other outputs as desired.
