### ISSUE TITLE
Fix Netlify deploy pipeline

### ISSUE THREAD

**Issue by jwflory** [sustainers/website#299]
In PR #298, the Netlify checks to build the site preview and deploy them in GitHub Pages is broken. It requires an administrator to debug. Maybe we need to re-authenticate or re-connect Netlify to our repository. Assigning to @RichardLitt.

**Comment by RichardLitt** [comment]
Not on my account. @jdorfman This on yours?

**Comment by jdorfman** [comment]
@jwflory @RichardLitt  yes it is under my personal account. We have 3 options

1. Remove @XhmikosR so I can add @jwflory (after 2 users, prices start at $15 / month)
2. Switch to GitHub Pages
3. Ask someone at Netlify for a free premium account 

Thoughts?

**Comment by RichardLitt** [comment]
Big fan of #3. Ideally, you and @jwflory and me should all have access. We're a 100% open source project, so that might work. 

GitHub pages doesn't do preview deploys, as far as I know.

**Comment by jwflory** [comment]
Option 3 is the least trouble for us and we don't have to spend time setting up a new CI pipeline.

Option 2 is my preferred fallback choice, and I prefer using Circle CI's platform if possible in the event we move. I can expand on my reasoning if this is the option we end up taking in the end.

**Comment by XhmikosR** [comment]
You can probably revert the bundler change in #298 and Netlify previews should work again. Otherwise, the `RUBY_VERSION` needs to change after that PR lands.

I don't mind removing me anyway.

Alternatives to your issues:

1. open-source Netlify plan: requires adding a logo to the main site, check their docs (to my eyes this is a wrong practice if the main site is built using Actions)
2. have a look at Cloudflare Pages; they recently launched it and it should work similarly
3. I'll see if I have some time to push a few updates

**Comment by jdorfman** [comment]
> have a look at Cloudflare Pages; they recently launched it and it should work similarly

Ah that is actually a great alt. We already use Cloudflare so this shouldn't be a difficult transition

**Comment by XhmikosR** [comment]
Netlify and prod deployments should be OK now.

That being said, I saw that GitHub Pages is in GA since yesterday so you guys could give it a go later. Also, you could probably just use Netlify or Cloudflare Pages to deploy the prod site too later.

The above is not needed right now, just putting it out there for the future.

PS. Feel free to CC me if you need help in the future; I don't have a lot of time, but I'll try to do my best to help.
