### ISSUE TITLE
Changelog's involvement day-of

### ISSUE THREAD

**Issue by whit537** [sustainers/website#55]
How do we mix in Changelog w/ Gunner's event format?

**Comment by whit537** [comment]
@jdorfman relays on (private) weekly call that we are planning to pay for @adamstac's flight, and he's committed to running Spotlight during the event. Sound right?

**Comment by jdorfman** [comment]
@whit537 this is a great point. I would like to run this by @alnermcgunn and see how we can do this without disrupting the agenda/flow.

I think there are 4 opportunities:

* Night before
* Coffee hour / check in 
* Lunch
* Happy hour

cc: @adamstac

**Comment by jdorfman** [comment]
wait is it @adamstac or @jerodsanto or both? I would love both fwiw.

**Comment by jerodsanto** [comment]
It'll be just me, because it conflicts with @adamstac's vacay.

**Comment by jdorfman** [comment]
well, that is perfect. I already met Adam IRL, now it is your turn @jerodsanto

**Comment by jerodsanto** [comment]
ok it's a deal but only if I get a hug 🤗 

It'd be great if we can produce 4-8 Spotlight episodes from the event. That means we need to line up those interviews, which could range from 15-45 minutes. Your bullet list looks good, except when do I get to eat lunch? 😉

As for who to interview, sometimes we set up things beforehand, sometimes we do it "man on the street" style where I just grab people who want to chat. Not sure what makes the most sense in this case, since there aren't any speakers or keynoters (which is usually who we schedule with).

**Comment by jdorfman** [comment]
> ok it's a deal but only if I get a hug 🤗

You are in luck, this year I dropped the price of hugs to $free.99

> It'd be great if we can produce 4-8 Spotlight episodes from the event. That means we need to line up those interviews, which could range from 15-45 minutes. 

👍 

> Your bullet list looks good, except when do I get to eat lunch? 😉

🤔  good point. Maybe just mute your mic when chewing? Kidding, need to think about this.

> As for who to interview, sometimes we set up things beforehand, sometimes we do it "man on the street" style where I just grab people who want to chat. 

I like that. People you don't recognize should be interview liked this.

> Not sure what makes the most sense in this case, since there aren't any speakers or keynoters (which is usually who we schedule with).

Organizers + Gunner

@whit537 and @piamancini are great because you can kind of do a follow up on episodes `#123` & `#234` respectively.

**Comment by whit537** [comment]
Don't forget `#87`! ☺️

**Comment by whit537** [comment]
... and if you have us both on at once you have to number it `#345`. 😉 💃

**Comment by jerodsanto** [comment]
All of this math is over my head! 🎓

**Comment by jdorfman** [comment]
@jerodsanto when do you get in? Day of or night before?

**Comment by jerodsanto** [comment]
We don't have travel plans lined up just yet, but I'm sure it'll be afternoon/night before.

**Comment by jdorfman** [comment]
@jerodsanto ok cool. What if we did the co-organizers (@piamancini @whit537 & me) + @alnermcgunn the night before. During the event, we will pick folks like @RichardLitt, @bkeepers, etc to go over to you throughout the day.

At night after the happy hour, we will do a wrap up with the co-organizers + @alnermcgunn (somewhere).

**Comment by jerodsanto** [comment]
I like that plan.

**Comment by jdorfman** [comment]
I think from here, I will create a "$ustain" calendar so we can start locking in times. Stay tuned

**Comment by alnermcgunn** [comment]
Justin, thanks for setting up the calendar. I would request that we hold off scheduling anything specific for day-of until the agenda has taken more shape, so that we don't schedule anything that is opposite program elements. One thing we can discuss on the next call is run-of-day, where we confirm lunch time etc, as that's pretty easy to nail down.

**Comment by jdorfman** [comment]
@alnermcgunn sounds good!

**Comment by whit537** [comment]
Talked about this on private weekly call. @jerodsanto and @alnermcgunn will have to work out the details, but it sounds like @jerodsanto is flexible ("we get great interviews every week, we don't need eight long interviews out of this event for it to be worth our while").

**Comment by piamancini** [comment]
closing this, was remains is sorting their travel plans

**Comment by jerodsanto** [comment]
@piamancini do you need me to take action on the travel planning? (feel free to Slack if it's easier)

**Comment by piamancini** [comment]
@jerodsanto yes please submit your travel plans on the doc so we can look at all the expenses together. Thank you! https://sustainoss.org/travel-support/

**Comment by jerodsanto** [comment]
Done and dusted
